name: Pre-release on push to main

on:
  push:
    branches:
      - main

jobs:
  version:
    uses: walt-id/waltid-identity/.github/workflows/version.yml@4ea41dd625cb070b2a513387f73acce468b12b45
    with:
      suffix: -SNAPSHOT
  gradle:
    uses: walt-id/waltid-identity/.github/workflows/gradle.yml@4ea41dd625cb070b2a513387f73acce468b12b45
    secrets: inherit
    needs: version
    with:
      version: ${{ needs.version.outputs.release_version }}
      publish: true
  docker-matrix:
    uses: walt-id/waltid-identity/.github/workflows/load-json.yml@4ea41dd625cb070b2a513387f73acce468b12b45
    with:
      jsonpath: ".github/workflows/data/docker-matrix.json"
  docker:
    uses: walt-id/waltid-identity/.github/workflows/docker.yml@4ea41dd625cb070b2a513387f73acce468b12b45
    secrets: inherit
    needs: [ version, docker-matrix ]
    with:
      images: ${{ needs.docker-matrix.outputs.json }}
      version: ${{ needs.version.outputs.release_version }}
      publish: true
  tag:
    uses: walt-id/waltid-identity/.github/workflows/tag.yml@4ea41dd625cb070b2a513387f73acce468b12b45
    needs: [ version, gradle, docker ]
    with:
      version: ${{ needs.version.outputs.release_version }}
  pre-release:
    uses: walt-id/waltid-identity/.github/workflows/changelog.yml@4ea41dd625cb070b2a513387f73acce468b12b45
    secrets: inherit
    needs: [ tag ]
    with:
      tag: ${{ needs.tag.outputs.tag }}